//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyKhoHang1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanlyKhoHang1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28689e64120315_5ac7733601504 {
            get {
                object obj = ResourceManager.GetObject("28689e64120315.5ac7733601504", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7etpgol5vni7a29jfbecupgimi {
            get {
                object obj = ResourceManager.GetObject("7etpgol5vni7a29jfbecupgimi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7etpgol5vni7a29jfbecupgimi1 {
            get {
                object obj = ResourceManager.GetObject("7etpgol5vni7a29jfbecupgimi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Adriana_Lima_by_Marcus_Cooper_LOfficiel_Italia_Sp_2022__3_ {
            get {
                object obj = ResourceManager.GetObject("Adriana-Lima-by-Marcus-Cooper-LOfficiel-Italia-Sp-2022+(3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgr {
            get {
                object obj = ResourceManager.GetObject("bgr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_icon_open_password_icon_1320183290851596683_16 {
            get {
                object obj = ResourceManager.GetObject("download-icon-open+password+icon-1320183290851596683_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download_icon_open_password_icon_1320183290851596683_256 {
            get {
                object obj = ResourceManager.GetObject("download-icon-open+password+icon-1320183290851596683_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_clipboard_cut_copy_and_paste_5ae0cc5c6668f8_4832143415246818204195 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-clipboard-cut-copy-and-paste-5ae0cc5c6668f8.48321434152468" +
                        "18204195", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_product_return_portable_network_gra_return_icon_other_dresses_dressesss_5b64f55ec4f5c3_4335079315333430708068 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-product-return-portable-network-gra-return-icon_other-dres" +
                        "ses_dressesss-5b64f55ec4f5c3.4335079315333430708068", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_service_computer_software_5b1ee3fb412f26_828696411528751099267 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-service-computer-software-5b1ee3fb412f26.82869641152875109" +
                        "9267", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_symbol_arrow_turn_around_and_look_around_5ad8d9cee46f47_3648666115241609749357 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-symbol-arrow-turn-around-and-look-around-5ad8d9cee46f47.36" +
                        "48666115241609749357", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_invoice_computer_icons_electronic_billing_receipt_invoices_vector_drawing_5ab1107237c5c1_4181590915215535222285 {
            get {
                object obj = ResourceManager.GetObject("kisspng-invoice-computer-icons-electronic-billing-receipt-invoices-vector-drawing" +
                        "-5ab1107237c5c1.4181590915215535222285", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_truong_dai_hoc_kien_truc_ha_noi_inkythuatso_01_23_13_08_25 {
            get {
                object obj = ResourceManager.GetObject("logo-truong-dai-hoc-kien-truc-ha-noi-inkythuatso-01-23-13-08-25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PikPng_com_twitter_icons_png_2837538 {
            get {
                object obj = ResourceManager.GetObject("PikPng.com_twitter-icons-png_2837538", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap position {
            get {
                object obj = ResourceManager.GetObject("position", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steven_Meisel_Vogue_1990_510x644 {
            get {
                object obj = ResourceManager.GetObject("Steven-Meisel-Vogue-1990-510x644", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steven_Meisel_Vogue_1990_510x6441 {
            get {
                object obj = ResourceManager.GetObject("Steven-Meisel-Vogue-1990-510x6441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steven_Meisel_Vogue_1990_510x6442 {
            get {
                object obj = ResourceManager.GetObject("Steven-Meisel-Vogue-1990-510x6442", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toppng_com_white_person_icon_man_icon_white_600x568 {
            get {
                object obj = ResourceManager.GetObject("toppng.com-white-person-icon-man-icon-white-600x568", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toppng_com_white_person_icon_people_white_icon_436x368 {
            get {
                object obj = ResourceManager.GetObject("toppng.com-white-person-icon-people-white-icon-436x368", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_avatar_icon_human_icon_person_icon_5d678454ee52e4_1566471415670651729762 {
            get {
                object obj = ResourceManager.GetObject("transparent-avatar-icon-human-icon-person-icon-5d678454ee52e4.1566471415670651729" +
                        "762", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
